### ISSUE TITLE
HutaoAPI ToDo

### ISSUE THREAD

**Issue by Lightczx** [DGP-Studio/Snap.Hutao.Server#1]
## 胡桃数据库API v2

Host: homa.snapgenshin.com

用户上传记录

- [x] Path: POST /Record/Upload

检查Uid记录是否存在

- [x] Path: GET /Record/Check?uid={}

获取实时排行信息

- [x] Path: GET /Record/Rank?uid={}

获取总览统计数据

- [x] Path: GET /Statistics/Overview

获取上场率

- [x] Path: GET /Statistics/Avatar/AttendanceRate

获取使用率

- [x] Path: GET /Statistics/Avatar/UtilizationRate

获取角色持有率

- [x] Path: GET /Statistics/Avatar/HoldingRate

获取角色/武器/圣遗物搭配

- [x] Path: GET /Statistics/Avatar/AvatarCollocation

获取队伍出场率

- [x] Path: GET /Statistics/Team/Combination

获取队伍搭配

- [ ] Path: POST /Statistics/Team/Recommended

**Comment by Lightczx** [comment]
## 祈愿记录API

Host: hutao-api.snapgenshin.com

获取祈愿记录
Path: GET /GachaLog/Retrive?uid={}

上传祈愿记录
Path POST /GachaLog/Upload

**Comment by Lightczx** [comment]
## 胡桃公告API

Host: hutao-api.snapgenshin.com

获取公告
Path: GET /Announcement?lastId={}

**Comment by Masterain98** [comment]
> ## 胡桃公告API
> Host: homa.snapgenshin.com
> 
> 获取公告 Path: GET /Announcement/List?lastId={}

多语言如何支持？

**Comment by Lightczx** [comment]
# 祈愿记录统计API

- [ ] 五星抽数分布
- [ ] 五星个数统计
- [ ] 分卡池的四五星个数统计
